#driver string to connect to postgresql
#jdbc.connection.string=jdbc:postgresql://localhost:5432/keyword?user=postgres&password=Unknown123
jdbc.connection.string=jdbc:postgresql://localhost:5432/postgres

# log in data
postgres.username=postgres
postgres.pwd=Unknown123

#the rdb schema where we are currently working (needed to interrogate the database)
schema=linkedmdb_1m

#big or small
database.size=big

#name of the database. If you do not have any particular requirements, keep default
#options so far: lubm, bsbm, dbpedia, default
rdf.database.name=default





# ---------- other labels to coordinate the input and output files ----------#
#primary directory of the algorithm. Gives the direction to all the rest
main.algorithm.directory=/Users/Nicola Maino/Documents/RDF/rLinkedMDB/systems/TSA

#the query directory, again a place where to start in order to read/write files
#deprecated, you can ignore this
main.query.directory=/Users/Nicola Maino/Documents/RDF_DATASETS/Dbpedia/systems/TSA/queries

terrier.home=/Users/Nicola Maino/terrier-custom

terrier.etc=/Users/Nicola Maino/offline_rdf_clustering/etc

#from where to read the queries
query.file=properties/lmdb_query_list.properties

on.line.time=1000
off.line.time=48








# --------- labels concerning the off-line phase ----------- #

#true: offline / false: online
is.offline=false


#legacy labels, you can keep these always at true
#they check the execution of the different parts of the off-line phase
#they were used for debugging reasons, to test one part at a time
#The very important label is 'is.offline'
#computation of statistics about nodes (phase 1)
statistics.computation.flag=false

#clustering (phases 2 and 3)
compute.top.k.connectivity.list.flag=true
clustering.phase.flag=true
# to trec documents (phase 4)
from.cluster.to.trec.documents.flag=true
#phase5 indexing
index.directory.of.trec.files.flag=true








# ---------- labels concerning the ON-LINE phase ----------#
#TSA+BM25
index.merged.collection.flag=false

#TSA+SLM
rj.collection.flag=false
rank.answers.flag=false

# TSA+MRF-KS
yosi.ranking.flag=false

#TSA+VDP
online.virtual.doc.and.pruning.on.the.fly.flag=false

#TSA+VDP+BACK, but this time with a backtracking flavour
tsa.vdp.back.flag=false

#TSA+BACK
tsa.back.flag=true














# ---------- labels about the OFFLINE-PHASE ---------- #

# ---------- phase 2

#set to true if you want to count the literals as neighbors
literal.flag=false

#where to save/read the partitions (second one used in phase 3 ClusteringPhase.java)
clusters.directory.path=/Users/Nicola Maino/Documents/RDF_DATASETS/rLinkedMDB/algorithms/TSA/clusters

#min number of occurrences in order to take a label
#LinkedMDB: 200, r-LinkedMDB: 20, r-IMDB: 200, IMDB: 200, LUBM1M: 100
#BSBM1M: 100
threshold=20

#max number of labels we are going to take
#LinkedMDB: 200, r-LinkedMDB: 200, r-IMDB: 30 (there are very few properties here)
#LUBM1M:  30, BSBM1M: 50
k=30

# ---------- phase 3
#LinkedMDB, r-LinkedMDB, r-IMDB. Our queries don't go beyond 2
tau=2

#4 LinkedMDB: 3, 4
#r-LinkedMDB: in 1, out 3 (because sometimes there is only 1 link to the node)
#r-IMDB: 2, 5,
#IMDB: 4, 5
#LUBM_1m: out 2, in 3
#BSBM1M: out 3, in 2
lambda.in=4
lambda.out=5




# ---------- TSA+BM25

answer.list.length=10000


#CRUCIAL
#rLMDB: 50, LinkedMDB: 20, IMDB: 40, LUBM1M: 20 - percentage of overlapping
compression.threshold=30
#rLMDB: 30, LinkedMDB: 5, IMDB: 10; LUBM1M: 10 - how many graphs are considered
lookahead.threshold=30

# ---------- TSA+VDP
#this is the number of the first top k graphs from the run file that we use
#to build the query graph. It represents the trade off between exploration of the whole
#set of potential answer graphs and the necessity to be quick
#make it smaller if the algorithm is not able to finish in time
#standard: 100
#LUBM: 250 but also 1000 is ok (little increment)
smart.traversal.limit=100

#tau of the BFS performed on the VDP phase when looking for answers
virtual.graphs.tau=3

#limitations on the number of answers extracted from
#one subgraph for the Backward algorithm
too.many.answers.for.this.algorithm=100
too.many.answers.for.this.subgraph=5
too.many.answers.for.one.root=5